video_path: data/raw/BlueWhales.mp4
detection_csv: outputs/detections/sample_detections_finetuned.csv
output_track_csv: outputs/tracks/sample_tracks_botsort_finetuned.csv

tracker:
  name: botsort
  reid_weights: osnet_x0_25_msmt17.pt
  device: cpu
  track_high_thresh: 0.7
  track_low_thresh: 0.65
  new_track_thresh: 0.2
  track_buffer: 30
  match_thresh: 0.8
  proximity_thresh: 0.7
  appearance_thresh: 0.6
  cmc_method: orb
  frame_rate: 30
  fuse_first_associate: False
  with_reid: True